server:
  port: 1111
  error.include-stacktrace: never

graphql:
  packages:
    - "com.example.demo"
  playground:
    endpoint: "/playground"
    enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/my_db
    username:
    password:
    hikari.maximumPoolSize: 40
